#!/bin/bash

BINFOLDERPATH="."
BINPATH="v4l2tohttp"
PARAMS="$@"

echo "starting $BINPATH with parameters $PARAMS"

if [ -e /usr/lib/x86_64-linux-gnu/libv4l/v4l2convert.so ]
then
  LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libv4l/v4l2convert.so $BINFOLDERPATH/$BINPATH $PARAMS
  exit 0
fi

if [ -e /usr/lib/libv4l/v4l2convert.so ]
then
  LD_PRELOAD=/usr/lib/libv4l/v4l2convert.so $BINFOLDERPATH/$BINPATH $PARAMS
  exit 0
fi

if [ -e /usr/lib32/libv4l/v4l2convert.so ]
then
  LD_PRELOAD=/usr/lib32/libv4l/v4l2convert.so $BINFOLDERPATH/$BINPATH $PARAMS
  exit 0
fi

if [ -e /usr/lib/i386-linux-gnu/libv4l/v4l2convert.so ]
then
  LD_PRELOAD=/usr/lib/i386-linux-gnu/libv4l/v4l2convert.so $BINFOLDERPATH/$BINPATH $PARAMS
  exit 0
fi
 
echo "Oh no.. they must have changed filenames again .. or you are running this script in an untested distro" 
echo "Trying one last trick to find v4l2convert.so.. Please also make sure you run the apt-get-dependencies script..!" 

CUSTOM_PLACE=`sudo find / -name v4l2convert.so  | grep v4l2convert`

if [ -e "$CUSTOM_PLACE" ]
then
  LD_PRELOAD=$CUSTOM_PLACE $BINFOLDERPATH/$BINPATH $PARAMS
  exit 0
fi

exit 0